$ ./testcases/cloud_user/instances/instancetest.py --credpath=/home/hspencer/admin-creds/ --emi emi-8C9B35F9 --tests BasicInstanceChecks MetaData Reboot --instance-user ec2-user
setuptestname:None
setup_debugmethod:
testcasename:None
log_level:None
logfile:None
logfile_level:debug
Starting setup_debugmethod, name:instancetest
After populating... setup_debugmethod: testcasename:Nonelog_level:debuglogfile:Nonelogfile_level:debug
[2013-07-12 08:44:25,486] [instancetest] [DEBUG]: instancetest: Eulogger init test message. Init complete
[2013-07-12 08:44:25,489] [instancetest] [DEBUG]: (setuptestcase:335): <pre>
[2013-07-12 08:44:25,492] [instancetest] [DEBUG]: (show_self:1307):
-------------------------------------------------------------------------
TESTCASE INFO:
----------
NAME:                     --->:  instancetest
TEST LIST:                --->:  []
CONFIG FILES:             --->:  []
-------------------------------------------------------------------------
[2013-07-12 08:44:25,495] [instancetest] [DEBUG]: (show_args:1328):
-------------------------------------------------------------------------
TEST ARGS:                       VALUE:
----------                      ------
debug_method              --->:  <bound method InstanceBasics.debug of <__main__.InstanceBasics testMethod=instancetest>>
logger                    --->:  <eutester.eulogger.Eulogger object at 0x2462510>
-------------------------------------------------------------------------
setup_debugmethod:
testcasename:None
log_level:None
logfile:None
logfile_level:None
Starting setup_debugmethod, name:instancetest
After populating... setup_debugmethod: testcasename:Nonelog_level:debuglogfile:Nonelogfile_level:debug
[2013-07-12 08:44:25,497] [instancetest] [DEBUG]: instancetest: Eulogger init test message. Init complete
[2013-07-12 08:44:25,500] [instancetest] [DEBUG]: (show_self:1307):
-------------------------------------------------------------------------
TESTCASE INFO:
----------
NAME:                     --->:  instancetest
TEST LIST:                --->:  []
CONFIG FILES:             --->:  []
-------------------------------------------------------------------------
[2013-07-12 08:44:25,504] [instancetest] [DEBUG]: (show_args:1328):
-------------------------------------------------------------------------
TEST ARGS:                       VALUE:
----------                      ------
args                      --->:  Namespace(config=None, config_file=None, configblocks=[], configfile=None, configsections=['MEMO', 'globals', 'instancetest'], cred_path='/home/hspencer/admin-creds/', credpath='/home/hspencer/admin-creds/', emi='emi-8C9B35F9', html_anchors=False, ignoreblocks=[], instance_passsword=None, instance_user='ec2-user', keypair=None, log_level='debug', logfile=None, logfile_level='debug', password=None, region=None, tests=['BasicInstanceChecks', 'MetaData', 'Reboot'], use_color=False, user_data=None, user_data_file=None, vmtype='c1.medium', zone=None)
config                    --->:  None
config_file               --->:  None
configblocks              --->:  []
configfile                --->:  None
configsections            --->:  ['MEMO', 'globals', 'instancetest']
cred_path                 --->:  /home/hspencer/admin-creds/
credpath                  --->:  /home/hspencer/admin-creds/
debug_method              --->:  <bound method InstanceBasics.debug of <__main__.InstanceBasics testMethod=instancetest>>
emi                       --->:  emi-8C9B35F9
html_anchors              --->:  False
ignoreblocks              --->:  []
instance_passsword        --->:  None
instance_user             --->:  ec2-user
keypair                   --->:  None
log_level                 --->:  debug
logfile                   --->:  None
logfile_level             --->:  debug
logger                    --->:  <eutester.eulogger.Eulogger object at 0x2462d50>
password                  --->:  None
region                    --->:  None
tests                     --->:  ['BasicInstanceChecks', 'MetaData', 'Reboot']
use_color                 --->:  False
user_data                 --->:  None
user_data_file            --->:  None
vmtype                    --->:  c1.medium
zone                      --->:  None
-------------------------------------------------------------------------
[2013-07-12 08:44:25,504] [EUCAOPS] [DEBUG]: EUCAOPS: Eulogger init test message. Init complete
[2013-07-12 08:44:25,514] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:124)Starting method: setup_ec2_connection(self, endpoint=10.104.1.216, aws_access_key_id=L4836KVYWMJCXT4T6Q6B9, aws_secret_access_key=XCJ6sZVFVfFMR4DNVIUL7N7e4cgk8ebvEW0ej5dZ, is_secure=False, host=None, region=None, path=/services/Eucalyptus, port=8773, APIVersion=2011-01-01, boto_debug=0)
[2013-07-12 08:44:25,514] [EUCAOPS] [DEBUG]: Attempting to create ec2 connection to 10.104.1.2168773/services/Eucalyptus
[2013-07-12 08:44:25,514] [EUCAOPS] [DEBUG]: Attempting to create IAM connection to 10.104.1.216:8773/services/Euare
[2013-07-12 08:44:25,527] [EUCAOPS] [DEBUG]: Attempting to create STS connection to 10.104.1.2168773/services/Eucalyptus
[2013-07-12 08:44:25,540] [EUCAOPS] [DEBUG]:
--->(cwops.py:122)Starting method: setup_cw_connection(self, endpoint=10.104.1.216, aws_access_key_id=L4836KVYWMJCXT4T6Q6B9, aws_secret_access_key=XCJ6sZVFVfFMR4DNVIUL7N7e4cgk8ebvEW0ej5dZ, is_secure=False, host=None, region=None, path=/services/CloudWatch, port=8773, boto_debug=0)
[2013-07-12 08:44:25,540] [EUCAOPS] [DEBUG]: Attempting to create cloud watch connection to 10.104.1.2168773/services/CloudWatch
[2013-07-12 08:44:25,541] [EUCAOPS] [DEBUG]: Attempting to create S3 connection to 10.104.1.216:8773/services/Walrus
[2013-07-12 08:44:25,541] [EUCAOPS] [DEBUG]: Unable to create AS connection because of: Unable to find AWS_AUTO_SCALING_URL id in eucarc
[2013-07-12 08:44:25,541] [EUCAOPS] [DEBUG]:
--->(elbops.py:88)Starting method: setup_elb_connection(self, endpoint=10.104.1.216, aws_access_key_id=L4836KVYWMJCXT4T6Q6B9, aws_secret_access_key=XCJ6sZVFVfFMR4DNVIUL7N7e4cgk8ebvEW0ej5dZ, is_secure=False, host=None, region=None, path=/services/LoadBalancing, port=8773, boto_debug=0)
[2013-07-12 08:44:25,541] [EUCAOPS] [DEBUG]: Attempting to create cloud watch connection to 10.104.1.2168773/services/LoadBalancing
[2013-07-12 08:44:25,542] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:358)Starting method: add_group(self, group_name=group-1373643865.54, description=None, fail_if_exists=False)
[2013-07-12 08:44:25,542] [EUCAOPS] [DEBUG]: Looking up group group-1373643865.54
[2013-07-12 08:44:25,618] [EUCAOPS] [DEBUG]: Creating Security Group: group-1373643865.54
[2013-07-12 08:44:25,743] [EUCAOPS] [DEBUG]: Found matching security group for name:group-1373643865.54 and id:None
[2013-07-12 08:44:25,743] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:418)Starting method: authorize_group_by_name(self, group_name=group-1373643865.54, port=22, protocol=tcp, cidr_ip=0.0.0.0/0)
[2013-07-12 08:44:25,743] [EUCAOPS] [DEBUG]: Attempting authorization of group-1373643865.54 on port 22 tcp
[2013-07-12 08:44:25,812] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:418)Starting method: authorize_group_by_name(self, group_name=group-1373643865.54, port=-1, protocol=icmp, cidr_ip=0.0.0.0/0)
[2013-07-12 08:44:25,812] [EUCAOPS] [DEBUG]: Attempting authorization of group-1373643865.54 on port -1 icmp
[2013-07-12 08:44:25,870] [EUCAOPS] [DEBUG]: Looking up keypair keypair-1373643865.87
[2013-07-12 08:44:25,901] [EUCAOPS] [DEBUG]: Creating keypair: keypair-1373643865.87
Creating testunit:BasicInstanceChecks, args:
[2013-07-12 08:44:26,362] [instancetest] [DEBUG]: (populate_testunit_with_args:1346): Attempting to populate testunit:BasicInstanceChecks, with testcase.args...
[2013-07-12 08:44:26,365] [instancetest] [DEBUG]: (populate_testunit_with_args:1354): Testunit keyword args:{}
[2013-07-12 08:44:26,368] [instancetest] [DEBUG]: (populate_testunit_with_args:1359): Got method args:('self',)
[2013-07-12 08:44:26,371] [instancetest] [DEBUG]: (populate_testunit_with_args:1367): test unit total args:{}
Creating testunit:MetaData, args:
[2013-07-12 08:44:26,374] [instancetest] [DEBUG]: (populate_testunit_with_args:1346): Attempting to populate testunit:MetaData, with testcase.args...
[2013-07-12 08:44:26,377] [instancetest] [DEBUG]: (populate_testunit_with_args:1354): Testunit keyword args:{}
[2013-07-12 08:44:26,380] [instancetest] [DEBUG]: (populate_testunit_with_args:1359): Got method args:('self',)
[2013-07-12 08:44:26,382] [instancetest] [DEBUG]: (populate_testunit_with_args:1367): test unit total args:{}
Creating testunit:Reboot, args:
[2013-07-12 08:44:26,385] [instancetest] [DEBUG]: (populate_testunit_with_args:1346): Attempting to populate testunit:Reboot, with testcase.args...
[2013-07-12 08:44:26,388] [instancetest] [DEBUG]: (populate_testunit_with_args:1354): Testunit keyword args:{}
[2013-07-12 08:44:26,391] [instancetest] [DEBUG]: (populate_testunit_with_args:1359): Got method args:('self', 'zone')
[2013-07-12 08:44:26,393] [instancetest] [DEBUG]: (populate_testunit_with_args:1367): test unit total args:{}
[2013-07-12 08:44:26,396] [instancetest] [DEBUG]: (populate_testunit_with_args:1373): Found matching arg for:zone
[2013-07-12 08:44:26,399] [instancetest] [DEBUG]: (print_test_unit_startmsg:863):
-------------------------------------------------------------------------
STARTING TESTUNIT: BasicInstanceChecks
METHOD:BasicInstanceChecks, TEST DESCRIPTION:

        This Case Was Developed To Run Through A Series Of Basic Instance Tests.
             The Tests Are As Follows:
                   - Execute Run_Instances Command
                   - Make Sure That Public Dns Name And Private Ip Aren'T The Same
                       (This Is For Managed/Managed-Novlan Networking Modes)
                   - Test To See If Instance Is Ping-Able
                   - Test To Make Sure That Instance Is Accessible Via Ssh
                       (Ssh Into Instance And Run Basic Ls Command)
             If Any Of These Tests Fail, The Test Case Will Error Out, Logging The Results.

End on Failure:False
Passing ARGS:""
Running list method: "BasicInstanceChecks()"
-------------------------------------------------------------------------
[2013-07-12 08:44:26,399] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:2235)Starting method: run_instance(self, image=emi-8C9B35F9, keypair=keypair-1373643865.87, group=group-1373643865.54, type=None, zone=LayinDaSmackDown, min=1, max=1, user_data=None, private_addressing=False, username=ec2-user, password=None, is_reachable=True, monitoring_enabled=False, timeout=480)
[2013-07-12 08:44:26,399] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:1881)Starting method: get_images(self, emi=emi-8C9B35F9, root_device_type=None, root_device_name=None, location=None, state=available, arch=None, owner_id=None, filters=None, not_location=None, max_count=1)
[2013-07-12 08:44:26,709] [EUCAOPS] [DEBUG]: Got 34 images matching prefix: emi-8C9B35F9, now filtering...
[2013-07-12 08:44:26,709] [EUCAOPS] [DEBUG]: Returning image:emi-8C9B35F9
[2013-07-12 08:44:26,709] [EUCAOPS] [DEBUG]: Attempting to run instance-store image Image:emi-8C9B35F9 in group group-1373643865.54
[2013-07-12 08:44:26,956] [EUCAOPS] [DEBUG]: Beginning poll loop for the 1 instance found in [Instance:i-AA173E9B]
[2013-07-12 08:44:26,956] [EUCAOPS] [DEBUG]: Beginning poll loop for instance Instance:i-AA173E9B to go to running
[2013-07-12 08:44:27,053] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(pending), elapsed:0/480
[2013-07-12 08:44:37,179] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(pending), elapsed:10/480
[2013-07-12 08:44:47,293] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(running) time elapsed (20)
[2013-07-12 08:44:47,293] [EUCAOPS] [DEBUG]: Instance:i-AA173E9B is now in running
[2013-07-12 08:44:47,293] [EUCAOPS] [DEBUG]: Instance i-AA173E9B now in running state  in zone: LayinDaSmackDown
[2013-07-12 08:44:47,293] [EUCAOPS] [DEBUG]: Instance:i-AA173E9B got Public IP: 10.104.7.11 Private IP: 172.17.119.10 Public DNS Name: 10.104.7.11 Private DNS Name: 172.17.119.10
[2013-07-12 08:44:47,293] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:2862)Starting method: wait_for_valid_ip(self, instances=Instance:i-AA173E9B, private_addressing=False, poll_interval=10, timeout=60)
[2013-07-12 08:44:47,375] [EUCAOPS] [DEBUG]: i-AA173E9B: FOUND public ip. Current:10.104.7.11, elapsed:0/60
[2013-07-12 08:44:47,375] [EUCAOPS] [DEBUG]: Check_system_for_dup_ip starting...
[2013-07-12 08:44:47,553] [EUCAOPS] [DEBUG]: Checking reservation: r-90B04320
[2013-07-12 08:44:47,553] [EUCAOPS] [DEBUG]: Checking instance i-A8733C82          , state:running              pubip:10.104.7.10          privip:172.17.114.174
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Checking reservation: r-D97C430D
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Checking instance i-AA173E9B          , state:running              pubip:10.104.7.11          privip:172.17.119.10
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Checking reservation: r-FA913DC4
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Checking instance i-89513E98          , state:running              pubip:10.104.7.12          privip:172.17.114.175
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Done with check_system_for_dup_ip
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Wait_for_valid_ip done
[2013-07-12 08:44:47,554] [EUCAOPS] [DEBUG]: Attempting to ping 10.104.7.11
[2013-07-12 08:44:50,560] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 19 more times
[2013-07-12 08:44:50,560] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:44:55,567] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 18 more times
[2013-07-12 08:44:55,567] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:00,574] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 17 more times
[2013-07-12 08:45:00,574] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:05,580] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 16 more times
[2013-07-12 08:45:05,580] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:10,587] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 15 more times
[2013-07-12 08:45:10,587] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:15,593] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 14 more times
[2013-07-12 08:45:15,593] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:20,600] [EUCAOPS] [DEBUG]: Ping unsuccessful retrying in 2 seconds 13 more times
[2013-07-12 08:45:20,601] [EUCAOPS] [DEBUG]: Sleeping for 2 seconds
[2013-07-12 08:45:24,722] [EUCAOPS] [DEBUG]: Was able to ping address
[2013-07-12 08:45:24,722] [EUCAOPS] [DEBUG]: Converting Reservation:r-D97C430D into euinstances
[2013-07-12 08:45:24,770] [i-AA173E9B] [DEBUG]: i-AA173E9B: Eulogger init test message. Init complete
[2013-07-12 08:45:25,073] [EUCAOPS] [DEBUG]:
--->(euzone.py:70)Starting method: get_all_vm_type_info(self)
[2013-07-12 08:45:25,107] [i-AA173E9B] [DEBUG]: Attempting to reconnect_to_instance:i-AA173E9B
[2013-07-12 08:45:25,227] [i-AA173E9B] [DEBUG]: reset_ssh_connection for:i-AA173E9B
[2013-07-12 08:45:25,227] [i-AA173E9B] [DEBUG]: Connecting ssh i-AA173E9B
[2013-07-12 08:45:25,227] [i-AA173E9B] [DEBUG]: SSH connection has hostname:10.104.7.11 user:ec2-user and keypath: /home/hspencer/eutester/keypair-1373643865.87.pem
[2013-07-12 08:45:25,229] [i-AA173E9B] [DEBUG]: Caught exception attempting to reconnect ssh:Unable to connect to 10.104.7.11: [Errno 111] Connection refused
[2013-07-12 08:45:25,229] [i-AA173E9B] [DEBUG]: connect_to_instance: Attempts:1, elapsed:0/422
[2013-07-12 08:45:30,324] [i-AA173E9B] [DEBUG]: reset_ssh_connection for:i-AA173E9B
[2013-07-12 08:45:30,324] [i-AA173E9B] [DEBUG]: Connecting ssh i-AA173E9B
[2013-07-12 08:45:30,324] [i-AA173E9B] [DEBUG]: SSH connection has hostname:10.104.7.11 user:ec2-user and keypath: /home/hspencer/eutester/keypair-1373643865.87.pem
[2013-07-12 08:45:30,429] [i-AA173E9B] [DEBUG]: SSH connection attempt(1 of 3), host:'ec2-user@10.104.7.11', using ipv4:10.104.7.11, thru proxy:'None'
[2013-07-12 08:45:31,196] [i-AA173E9B] [DEBUG]: SSH - Connected to 10.104.7.11
[2013-07-12 08:45:31,196] [i-AA173E9B] [DEBUG]: Try some sys...
[2013-07-12 08:45:31,196] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]#
[2013-07-12 08:45:31,613] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:31,664] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:31,664] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# dmesg | grep vda
[2013-07-12 08:45:31,719] [i-AA173E9B] [DEBUG]:
Command line: root=/dev/vda1 console=ttyS0
Kernel command line: root=/dev/vda1 console=ttyS0
 vda: vda1 vda2 vda3
EXT3-fs (vda1): mounted filesystem with ordered data mode
dracut: Mounted root filesystem /dev/vda1
SELinux: initialized (dev vda1, type ext3), uses xattr
EXT3-fs (vda1): using internal journal
Adding 524280k swap on /dev/vda3.  Priority:-1 extents:1 across:524280k
EXT3-fs (vda2): using internal journal
EXT3-fs (vda2): mounted filesystem with ordered data mode
SELinux: initialized (dev vda2, type ext3), uses xattr

[2013-07-12 08:45:31,720] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:31,720] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# dmesg | grep xvda
[2013-07-12 08:45:31,789] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:31,789] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:31,789] [i-AA173E9B] [DEBUG]: []
[2013-07-12 08:45:31,790] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# dmesg | grep sda
[2013-07-12 08:45:31,851] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:31,851] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:31,851] [i-AA173E9B] [DEBUG]: []
[2013-07-12 08:45:31,912] [EUCAOPS] [DEBUG]: Beginning poll loop for the 1 instance found in [Instance:i-AA173E9B]
[2013-07-12 08:45:31,912] [EUCAOPS] [DEBUG]: Beginning poll loop for instance Instance:i-AA173E9B to go to running
[2013-07-12 08:45:32,000] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(running) time elapsed (0)
[2013-07-12 08:45:32,000] [EUCAOPS] [DEBUG]: Instance:i-AA173E9B is now in running
[2013-07-12 08:45:32,001] [EUCAOPS] [DEBUG]: Attempting to ping 10.104.7.11
[2013-07-12 08:45:32,005] [EUCAOPS] [DEBUG]: Was able to ping address
[2013-07-12 08:45:32,005] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'ls -1 /dev/vda2'
[2013-07-12 08:45:32,061] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:32,061] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:32,065] [instancetest] [DEBUG]: (endsuccess:703):
-------------------------------------------------------------------------
- UNIT ENDED - BasicInstanceChecks
-------------------------------------------------------------------------

[2013-07-12 08:45:32,068] [instancetest] [DEBUG]: (run_test_case_list:807): RESULTS SUMMARY FOR 'instancetest':
[2013-07-12 08:45:32,068] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807): | TOTAL   | FAILED  | PASSED  | NOT_RUN | TIME_ELAPSED
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807): | 3       | 0       | 1       | 2       | 65
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:32,069] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:45:32,072] [instancetest] [DEBUG]: (print_test_unit_startmsg:863):
-------------------------------------------------------------------------
STARTING TESTUNIT: MetaData
METHOD:MetaData, TEST DESCRIPTION:

        This Case Was Developed To Test The Metadata Service Of An Instance For Consistency.
        The Following Meta-Data Attributes Are Tested:
           - Public-Keys/0/Openssh-Key
           - Security-Groups
           - Instance-Id
           - Local-Ipv4
           - Public-Ipv4
           - Ami-Id
           - Ami-Launch-Index
           - Reservation-Id
           - Placement/Availability-Zone
           - Kernel-Id
           - Public-Hostname
           - Local-Hostname
           - Hostname
           - Ramdisk-Id
           - Instance-Type
           - Any Bad Metadata That Shouldn'T Be Present.
        Missing Nodes
         ['Block-Device-Mapping/',  'Ami-Manifest-Path']
        If Any Of These Tests Fail, The Test Case Will Error Out; Logging The Results.

End on Failure:False
Passing ARGS:""
Running list method: "MetaData()"
-------------------------------------------------------------------------
[2013-07-12 08:45:32,157] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key'
[2013-07-12 08:45:32,245] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:32,296] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:32,351] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/security-groups'
[2013-07-12 08:45:32,432] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:32,482] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:32,538] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/instance-id'
[2013-07-12 08:45:32,615] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:32,665] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:32,721] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/local-ipv4'
[2013-07-12 08:45:32,789] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:32,789] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:32,907] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/public-ipv4'
[2013-07-12 08:45:32,981] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,031] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:33,087] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/ami-id'
[2013-07-12 08:45:33,172] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,172] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:33,290] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/ami-launch-index'
[2013-07-12 08:45:33,363] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,414] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:33,469] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/reservation-id'
[2013-07-12 08:45:33,542] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,592] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:33,648] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/placement/availability-zone'
[2013-07-12 08:45:33,723] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,773] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:33,828] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/kernel-id'
[2013-07-12 08:45:33,903] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:33,954] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:34,009] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/public-hostname'
[2013-07-12 08:45:34,084] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:34,134] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:34,190] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/local-hostname'
[2013-07-12 08:45:34,260] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:34,310] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:34,365] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'curl http://169.254.169.254/latest/meta-data/hostname'
[2013-07-12 08:45:34,435] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:34,485] [i-AA173E9B] [DEBUG]: done with exec

TESTUNIT FAILED: MetaDataTraceback (most recent call last):
  File "/home/hspencer/eutester-dev/lib/python2.6/site-packages/eutester-0.0.7-py2.6.egg/eutester/eutestcase.py", line 275, in run
    ret = self.method()
  File "./testcases/cloud_user/instances/instancetest.py", line 195, in MetaData
    self.assertTrue(re.match(instance.get_metadata("hostname")[0], instance.private_dns_name), 'Incorrect host name in metadata')
  File "/usr/lib64/python2.6/unittest.py", line 324, in failUnless
    if not expr: raise self.failureException, msg
AssertionError: Incorrect host name in metadata

[2013-07-12 08:45:34,507] [instancetest] [DEBUG]: (endsuccess:703):
-------------------------------------------------------------------------
- UNIT ENDED - MetaData
-------------------------------------------------------------------------

[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): RESULTS SUMMARY FOR 'instancetest':
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): | TOTAL   | FAILED  | PASSED  | NOT_RUN | TIME_ELAPSED
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): | 3       | 1       | 1       | 1       | 67
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:45:34,513] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:45:34,516] [instancetest] [DEBUG]: (print_test_unit_startmsg:863):
-------------------------------------------------------------------------
STARTING TESTUNIT: Reboot
METHOD:Reboot, TEST DESCRIPTION:

        This Case Was Developed To Test Ip Connectivity And Volume Attachment After
        Instance Reboot.  The Following Tests Are Done For This Test Case:
                   - Creates A 1 Gig Ebs Volume, Then Attach Volume
                   - Reboot Instance
                   - Attempts To Connect To Instance Via Ssh
                   - Checks To See If Ebs Volume Is Attached
                   - Detaches Volume
                   - Deletes Volume
        If Any Of These Tests Fail, The Test Case Will Error Out; Logging The Results.

End on Failure:False
Passing ARGS:
---------------------
zone : None
---------------------
Running list method: "Reboot(zone:None)"
-------------------------------------------------------------------------
KWARG:zone = None
[2013-07-12 08:45:34,516] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:524)Starting method: create_volume(self, zone=LayinDaSmackDown, size=1, eof=True, snapshot=None, timeout=0, poll_interval=10, timepergig=120)
[2013-07-12 08:45:34,517] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:543)Starting method: create_volumes(self, zone=LayinDaSmackDown, size=1, count=1, mincount=1, eof=True, monitor_to_state=available, delay=0, snapshot=None, timeout=0, poll_interval=10, timepergig=120)
[2013-07-12 08:45:34,517] [EUCAOPS] [DEBUG]: Sending create volume request, count:1
[2013-07-12 08:45:34,728] [EUCAOPS] [DEBUG]: 1/1 requests for volume creation succeeded.
[2013-07-12 08:45:34,728] [EUCAOPS] [DEBUG]:

-----------------------------------------------------------------------------------------------------------------------------------------------
VOL_ID         |ORDER|LASTSTATUS|TESTSTATUS|   AGE@STATUS  |SIZE|   FROM_SNAP   |             MD5_SUM             |MD5LEN|      ZONE     |INSTANCE
-----------------------------------------------------------------------------------------------------------------------------------------------
vol-A80E40D5   |  0  | creating | creating |       0       | 1  |      None     |               None              |  32  |LayinDaSmackDown|None
-----------------------------------------------------------------------------------------------------------------------------------------------

[2013-07-12 08:45:34,728] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:642)Starting method: monitor_created_euvolumes_to_state(self, volumes=[Volume:vol-A80E40D5], eof=True, mincount=1, state=available, poll_interval=10, deletefailed=True, size=1, timepergig=120)
[2013-07-12 08:45:34,729] [EUCAOPS] [DEBUG]: Monitoring 1 volumes for at least 1 to reach state:available
[2013-07-12 08:45:34,729] [EUCAOPS] [DEBUG]: Monitoring 1 volumes for at least 1 to reach state:available
[2013-07-12 08:45:34,729] [EUCAOPS] [DEBUG]: Polling 1 volumes for status:"available"...
[2013-07-12 08:45:34,847] [EUCAOPS] [DEBUG]: Volume #0 (vol-A80E40D5) State(creating), seconds elapsed: 0/120
[2013-07-12 08:45:34,847] [EUCAOPS] [DEBUG]: ----Time Elapsed:0, Waiting on 1 volumes to enter state:available-----
[2013-07-12 08:45:44,961] [EUCAOPS] [DEBUG]: Volume #0 (vol-A80E40D5) State(available), seconds elapsed: 10/120
[2013-07-12 08:45:44,962] [EUCAOPS] [DEBUG]: ----Time Elapsed:10, Waiting on 0 volumes to enter state:available-----
[2013-07-12 08:45:44,962] [EUCAOPS] [DEBUG]:

-----------------------------------------------------------------------------------------------------------------------------------------------
VOL_ID         |ORDER|LASTSTATUS|TESTSTATUS|   AGE@STATUS  |SIZE|   FROM_SNAP   |             MD5_SUM             |MD5LEN|      ZONE     |INSTANCE
-----------------------------------------------------------------------------------------------------------------------------------------------
vol-A80E40D5   |  0  |available |available |     10.44     | 1  |      None     |               None              |  32  |LayinDaSmackDown|None
-----------------------------------------------------------------------------------------------------------------------------------------------

[2013-07-12 08:45:44,962] [i-AA173E9B] [DEBUG]: Attempting to attach volume:vol-A80E40D5 to instance:i-AA173E9B to dev:None
[2013-07-12 08:45:44,963] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c "ls -1 /dev/ | grep '^sd\|^vd\|^xd\|^xvd'"
[2013-07-12 08:45:45,018] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:45,019] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:45,019] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'dmesg | grep vda'
[2013-07-12 08:45:45,089] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:45,089] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:45,089] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'dmesg | grep xvda'
[2013-07-12 08:45:45,159] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:45,159] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:45,159] [i-AA173E9B] [DEBUG]: []
[2013-07-12 08:45:45,159] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'dmesg | grep sda'
[2013-07-12 08:45:45,228] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:45:45,229] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:45:45,229] [i-AA173E9B] [DEBUG]: []
[2013-07-12 08:45:45,229] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:2139)Starting method: get_volumes(self, volume_id=vol-, status=None, attached_instance=i-AA173E9B, attached_dev=None, snapid=None, zone=None, filters=None, minsize=1, maxsize=None, md5=None, eof=False)
[2013-07-12 08:45:45,639] [i-AA173E9B] [DEBUG]: Instance:i-AA173E9B returning available cloud scsi dev:/dev/vde
[2013-07-12 08:45:45,639] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:1033)Starting method: attach_volume(self, instance=Instance:i-AA173E9B, volume=Volume:vol-A80E40D5, device_path=/dev/vde, pause=10, timeout=180)
[2013-07-12 08:45:45,640] [EUCAOPS] [DEBUG]: Sending attach for Volume:vol-A80E40D5 to be attached to Instance:i-AA173E9B at requested device  /dev/vde
[2013-07-12 08:45:46,157] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5, state:in-use, attached status:attaching, elapsed:0/180
[2013-07-12 08:45:46,157] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:45:56,296] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5, state:in-use, attached status:attaching, elapsed:10/180
[2013-07-12 08:45:56,296] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:46:06,428] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5, state:in-use, attached status:attaching, elapsed:20/180
[2013-07-12 08:46:06,428] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:46:16,567] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5, Attached: in-use - attached, elapsed:30
[2013-07-12 08:46:16,567] [i-AA173E9B] [DEBUG]: Checking for volume attachment on guest, elapsed time(0)
[2013-07-12 08:46:16,567] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c "ls -1 /dev/ | grep '^sd\|^vd\|^xd\|^xvd'"
[2013-07-12 08:46:16,630] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:16,631] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:16,631] [i-AA173E9B] [DEBUG]: dev_list_after:sda sda1 sda2 sda3 sdb vda vda1 vda2 vda3 vdb
[2013-07-12 08:46:16,631] [i-AA173E9B] [DEBUG]: Volume:vol-A80E40D5 guest device:/dev/vdb
[2013-07-12 08:46:16,631] [i-AA173E9B] [DEBUG]: vol-A80E40D5 Requested dev:/dev/vde, attached to guest device:/dev/vdb
[2013-07-12 08:46:16,631] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'head -c 32 /dev/vdb | xargs -0 printf %s | wc -c'
[2013-07-12 08:46:16,789] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:16,840] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:16,840] [i-AA173E9B] [DEBUG]:
--->(euinstance.py:792)Starting method: random_fill_volume(self, euvolume=Volume:vol-A80E40D5, srcdev=None, length=32, timepergig=90)
[2013-07-12 08:46:16,841] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'ls /dev/vdb'
[2013-07-12 08:46:16,900] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:16,900] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:16,900] [i-AA173E9B] [DEBUG]: exit code:0
[2013-07-12 08:46:16,900] [i-AA173E9B] [DEBUG]: File /dev/vdb is present on i-AA173E9B
[2013-07-12 08:46:16,900] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'ls /dev/urandom'
[2013-07-12 08:46:16,969] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:16,969] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:16,970] [i-AA173E9B] [DEBUG]:
--->(euinstance.py:857)Starting method: dd_monitor(self, ddif=None, ddof=None, ddcount=None, ddbs=1024, ddbytes=None, ddcmd=echo vol-A80E40D5 | dd of=/dev/vdb, ddseek=None, timeout=90, poll_interval=1, tmpfile=None)
[2013-07-12 08:46:16,970] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'nohup echo vol-A80E40D5 | dd of=/dev/vdb 2> /tmp/eutesterddcmd.1373643976 & echo $! && sleep 2'
[2013-07-12 08:46:17,025] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:19,041] [i-AA173E9B] [DEBUG]: done with exec

----------------------------------------------------------------------------------------------------------------------------
DD DATA INFO                            |     DD TIME INFO    |       DD RATE INFO      |     DD RECORDS FULL/PARTIAL INFO
----------------------------------------------------------------------------------------------------------------------------
BYTES          |      MBs      |  GIGs  | DD TIME  |TEST TIME |  DD RATE   | TEST RATE  |      REC_IN      |     REC_OUT
----------------------------------------------------------------------------------------------------------------------------
13             |      0.0      |  0.0   |0.00261492|  2.1986  |  5.0 kB/s  |  0.0 MB/s  |     F:0 P:1      |     F:0 P:1
----------------------------------------------------------------------------------------------------------------------------
[2013-07-12 08:46:20,170] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'sync'
[2013-07-12 08:46:20,262] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:20,313] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:20,313] [i-AA173E9B] [DEBUG]: Done with dd, copied 13 over elapsed:3
[2013-07-12 08:46:20,313] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'rm -f /tmp/eutesterddcmd.1373643976'
[2013-07-12 08:46:20,368] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:20,369] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:20,369] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'rm -f /tmp/eutesterddcmd.1373643976.pid'
[2013-07-12 08:46:20,439] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:20,439] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:20,439] [i-AA173E9B] [DEBUG]: length remaining to write after adding volumeid:19
[2013-07-12 08:46:20,440] [i-AA173E9B] [DEBUG]:
--->(euinstance.py:857)Starting method: dd_monitor(self, ddif=/dev/urandom, ddof=/dev/vdb, ddcount=None, ddbs=19, ddbytes=19, ddcmd=None, ddseek=13, timeout=90, poll_interval=1, tmpfile=None)
[2013-07-12 08:46:20,440] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'nohup dd if=/dev/urandom of=/dev/vdb seek=13  bs=19  count=1  2> /tmp/eutesterddcmd.1373643980 & echo $! && sleep 2'
[2013-07-12 08:46:20,509] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:22,529] [i-AA173E9B] [DEBUG]: done with exec

----------------------------------------------------------------------------------------------------------------------------
DD DATA INFO                            |     DD TIME INFO    |       DD RATE INFO      |     DD RECORDS FULL/PARTIAL INFO
----------------------------------------------------------------------------------------------------------------------------
BYTES          |      MBs      |  GIGs  | DD TIME  |TEST TIME |  DD RATE   | TEST RATE  |      REC_IN      |     REC_OUT
----------------------------------------------------------------------------------------------------------------------------
19             |      0.0      |  0.0   |0.00137882|  2.2058  | 13.8 kB/s  |  0.0 MB/s  |     F:1 P:0      |     F:1 P:0
----------------------------------------------------------------------------------------------------------------------------
[2013-07-12 08:46:23,646] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'sync'
[2013-07-12 08:46:23,825] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:23,875] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:23,875] [i-AA173E9B] [DEBUG]: Done with dd, copied 19 over elapsed:3
[2013-07-12 08:46:23,875] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'rm -f /tmp/eutesterddcmd.1373643980'
[2013-07-12 08:46:23,931] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:23,931] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:23,931] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'rm -f /tmp/eutesterddcmd.1373643980.pid'
[2013-07-12 08:46:23,992] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:23,992] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:23,992] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'ls /dev/vdb'
[2013-07-12 08:46:24,053] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:24,054] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:24,054] [i-AA173E9B] [DEBUG]: exit code:0
[2013-07-12 08:46:24,054] [i-AA173E9B] [DEBUG]: File /dev/vdb is present on i-AA173E9B
[2013-07-12 08:46:24,054] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'head -c 32 /dev/vdb | md5sum'
[2013-07-12 08:46:24,115] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:24,115] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:24,115] [i-AA173E9B] [DEBUG]: Got MD5 for Volume:vol-A80E40D5 dev:/dev/vdb md5:448562eb80bab642a48b2bf08d0e3688
[2013-07-12 08:46:24,115] [i-AA173E9B] [DEBUG]: Filled Volume:vol-A80E40D5 dev:/dev/vdb md5:448562eb80bab642a48b2bf08d0e3688
[2013-07-12 08:46:24,116] [i-AA173E9B] [DEBUG]: Success attaching volume:vol-A80E40D5 to instance:i-AA173E9B, cloud dev:/dev/vde, attached dev:/dev/vdb
[2013-07-12 08:46:24,116] [i-AA173E9B] [DEBUG]: Attempting to reboot instance:i-AA173E9B, check attached volume state first
[2013-07-12 08:46:24,116] [EUCAOPS] [DEBUG]: Beginning poll loop for result get_safe_uptime to go to None
[2013-07-12 08:46:24,116] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'cat /proc/uptime'
[2013-07-12 08:46:24,177] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:24,177] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:24,177] [EUCAOPS] [DEBUG]: get_safe_uptime returned: "51" after 0 minutes 0 seconds.
[2013-07-12 08:46:24,178] [i-AA173E9B] [DEBUG]: Rebooting now...
[2013-07-12 08:46:44,311] [i-AA173E9B] [DEBUG]: Attempting to reconnect_to_instance:i-AA173E9B
[2013-07-12 08:46:44,425] [i-AA173E9B] [DEBUG]: reset_ssh_connection for:i-AA173E9B
[2013-07-12 08:46:44,425] [i-AA173E9B] [DEBUG]: Connecting ssh i-AA173E9B
[2013-07-12 08:46:44,426] [i-AA173E9B] [DEBUG]: SSH connection has hostname:10.104.7.11 user:ec2-user and keypath: /home/hspencer/eutester/keypair-1373643865.87.pem
[2013-07-12 08:46:45,426] [i-AA173E9B] [DEBUG]: Caught exception attempting to reconnect ssh:Unable to connect to 10.104.7.11: [Errno 111] Connection refused
[2013-07-12 08:46:45,427] [i-AA173E9B] [DEBUG]: connect_to_instance: Attempts:1, elapsed:1/300
[2013-07-12 08:46:50,519] [i-AA173E9B] [DEBUG]: reset_ssh_connection for:i-AA173E9B
[2013-07-12 08:46:50,519] [i-AA173E9B] [DEBUG]: Connecting ssh i-AA173E9B
[2013-07-12 08:46:50,519] [i-AA173E9B] [DEBUG]: SSH connection has hostname:10.104.7.11 user:ec2-user and keypath: /home/hspencer/eutester/keypair-1373643865.87.pem
[2013-07-12 08:46:50,608] [i-AA173E9B] [DEBUG]: SSH connection attempt(1 of 3), host:'ec2-user@10.104.7.11', using ipv4:10.104.7.11, thru proxy:'None'
[2013-07-12 08:46:51,596] [i-AA173E9B] [DEBUG]: SSH - Connected to 10.104.7.11
[2013-07-12 08:46:51,596] [i-AA173E9B] [DEBUG]: Try some sys...
[2013-07-12 08:46:51,596] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c ''
[2013-07-12 08:46:51,802] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:51,803] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:51,803] [EUCAOPS] [DEBUG]: Beginning poll loop for result get_safe_uptime to go to None
[2013-07-12 08:46:51,804] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'cat /proc/uptime'
[2013-07-12 08:46:51,922] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:46:51,922] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:46:51,922] [EUCAOPS] [DEBUG]: get_safe_uptime returned: "7" after 0 minutes 0 seconds.
[2013-07-12 08:46:51,922] [i-AA173E9B] [DEBUG]: i-AA173E9B reboot_instance_and_verify Success
[2013-07-12 08:46:52,110] [EUCAOPS] [DEBUG]: Sent detach for volume: vol-A80E40D5 which is currently in state: in-use
[2013-07-12 08:46:52,212] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5 state:in-use, attached_data:detaching, pause:10, instance:i-AA173E9B, elapsed:0
[2013-07-12 08:46:52,213] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:47:02,347] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5 state:in-use, attached_data:detaching, pause:10, instance:i-AA173E9B, elapsed:10
[2013-07-12 08:47:02,347] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:47:12,483] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5 state:in-use, attached_data:detaching, pause:10, instance:i-AA173E9B, elapsed:20
[2013-07-12 08:47:12,483] [EUCAOPS] [DEBUG]: Sleeping for 10 seconds
[2013-07-12 08:47:22,612] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5 left in available
[2013-07-12 08:47:22,612] [i-AA173E9B] [DEBUG]: Wait for device:/dev/vdb to be removed on guest...
[2013-07-12 08:47:22,612] [i-AA173E9B] [DEBUG]: [ec2-user@10.104.7.11]# sudo sh -c 'ls /dev/vdb'
[2013-07-12 08:47:22,670] [i-AA173E9B] [DEBUG]:

[2013-07-12 08:47:22,670] [i-AA173E9B] [DEBUG]: done with exec
[2013-07-12 08:47:22,670] [i-AA173E9B] [DEBUG]: exit code:2
[2013-07-12 08:47:22,862] [EUCAOPS] [DEBUG]: Sent delete for volume: vol-A80E40D5, monitor to deleted state or failure
[2013-07-12 08:47:22,955] [EUCAOPS] [DEBUG]:
--->(ec2ops.py:2139)Starting method: get_volumes(self, volume_id=vol-A80E40D5, status=None, attached_instance=None, attached_dev=None, snapid=None, zone=None, filters=None, minsize=1, maxsize=None, md5=None, eof=True)
[2013-07-12 08:47:23,373] [EUCAOPS] [DEBUG]: Volume:vol-A80E40D5 in deleting sleeping:10, elapsed:0
[2013-07-12 08:47:33,388] [instancetest] [DEBUG]: (endsuccess:703):
-------------------------------------------------------------------------
- UNIT ENDED - Reboot
-------------------------------------------------------------------------

[2013-07-12 08:47:33,393] [instancetest] [DEBUG]: (run_test_case_list:807): RESULTS SUMMARY FOR 'instancetest':
[2013-07-12 08:47:33,393] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807): | TOTAL   | FAILED  | PASSED  | NOT_RUN | TIME_ELAPSED
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807): | 3       | 1       | 2       | 0       | 185
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807): ------------------------------------------------------
[2013-07-12 08:47:33,394] [instancetest] [DEBUG]: (run_test_case_list:807):
[2013-07-12 08:47:33,397] [instancetest] [DEBUG]: (run_test_case_list:816): Printing pre-cleanup results:
[2013-07-12 08:47:33,400] [instancetest] [DEBUG]: (<lambda>:959): Test list results for testcase:instancetest
[2013-07-12 08:47:33,403] [instancetest] [DEBUG]: (run_test_case_list:818):
-------------------------------------------------------------------------
RUN TEST CASE LIST DONE:
Ran 3/3 tests in 186 seconds

TESTUNIT LIST SUMMARY FOR instancetest

--------------------------------------------------------------------------------
                    | RESULT: passed
                    | TEST NAME: BasicInstanceChecks
                    | TIME : 65
                    | ARGS: BasicInstanceChecks()
--------------------------------------------------------------------------------
                    | RESULT: failed
                    | TEST NAME: MetaData
                    | TIME : 2
                    | ARGS: MetaData()
ERROR:(MetaData): Incorrect host name in metadata

--------------------------------------------------------------------------------
                    | RESULT: passed
                    | TEST NAME: Reboot
                    | TIME : 118
                    | ARGS: Reboot(zone:None)
--------------------------------------------------------------------------------
RESULTS SUMMARY FOR 'instancetest':

------------------------------------------------------
| TOTAL   | FAILED  | PASSED  | NOT_RUN | TIME_ELAPSED
------------------------------------------------------
| 3       | 1       | 2       | 0       | 185
------------------------------------------------------


-------------------------------------------------------------------------
Creating testunit:clean_method, args:
[2013-07-12 08:47:33,406] [instancetest] [DEBUG]: (populate_testunit_with_args:1346): Attempting to populate testunit:clean_method, with testcase.args...
[2013-07-12 08:47:33,409] [instancetest] [DEBUG]: (populate_testunit_with_args:1354): Testunit keyword args:{}
[2013-07-12 08:47:33,411] [instancetest] [DEBUG]: (populate_testunit_with_args:1359): Got method args:('self',)
[2013-07-12 08:47:33,414] [instancetest] [DEBUG]: (populate_testunit_with_args:1367): test unit total args:{}
[2013-07-12 08:47:33,417] [instancetest] [DEBUG]: (print_test_unit_startmsg:863):
-------------------------------------------------------------------------
STARTING TESTUNIT: clean_method
METHOD:clean_method, TEST DESCRIPTION:

End on Failure:False
Passing ARGS:""
Running list method: "clean_method()"
-------------------------------------------------------------------------
[2013-07-12 08:47:33,417] [EUCAOPS] [DEBUG]: Starting cleanup of artifacts
[2013-07-12 08:47:33,417] [EUCAOPS] [DEBUG]: Sending terminate for Instance:i-AA173E9B
[2013-07-12 08:47:33,543] [EUCAOPS] [DEBUG]: Beginning poll loop for the 1 instance found in [Instance:i-AA173E9B]
[2013-07-12 08:47:33,543] [EUCAOPS] [DEBUG]: Beginning poll loop for instance Instance:i-AA173E9B to go to terminated
[2013-07-12 08:47:33,610] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(shutting-down), elapsed:0/480
[2013-07-12 08:47:43,705] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(shutting-down), elapsed:10/480
[2013-07-12 08:47:53,781] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(terminated) time elapsed (20)
[2013-07-12 08:47:53,781] [EUCAOPS] [DEBUG]: Instance:i-AA173E9B is now in terminated
[2013-07-12 08:47:53,781] [EUCAOPS] [DEBUG]: clean_up_test_volumes starting, volumes:test_resources['volumes']
[2013-07-12 08:47:53,781] [EUCAOPS] [DEBUG]: Deleting SecurityGroup:group-1373643865.54
[2013-07-12 08:47:53,855] [EUCAOPS] [DEBUG]: Deleting Reservation:r-D97C430D
[2013-07-12 08:47:53,855] [EUCAOPS] [DEBUG]: Sending terminate for Instance:i-AA173E9B
[2013-07-12 08:47:53,894] [EUCAOPS] [DEBUG]: Beginning poll loop for the 1 instance found in [Instance:i-AA173E9B]
[2013-07-12 08:47:53,895] [EUCAOPS] [DEBUG]: Beginning poll loop for instance Instance:i-AA173E9B to go to terminated
[2013-07-12 08:47:53,995] [EUCAOPS] [DEBUG]: Instance(i-AA173E9B) State(terminated) time elapsed (0)
[2013-07-12 08:47:53,995] [EUCAOPS] [DEBUG]: Instance:i-AA173E9B is now in terminated
[2013-07-12 08:47:53,995] [EUCAOPS] [DEBUG]: Deleting KeyPair:keypair-1373643865.87
[2013-07-12 08:47:54,051] [instancetest] [DEBUG]: (<lambda>:959): Test list results for testcase:instancetest
[2013-07-12 08:47:54,056] [instancetest] [DEBUG]: (run_test_case_list:834):
-------------------------------------------------------------------------

TESTUNIT LIST SUMMARY FOR instancetest

--------------------------------------------------------------------------------
                    | RESULT: passed
                    | TEST NAME: BasicInstanceChecks
                    | TIME : 65
                    | ARGS: BasicInstanceChecks()
--------------------------------------------------------------------------------
                    | RESULT: failed
                    | TEST NAME: MetaData
                    | TIME : 2
                    | ARGS: MetaData()
ERROR:(MetaData): Incorrect host name in metadata

--------------------------------------------------------------------------------
                    | RESULT: passed
                    | TEST NAME: Reboot
                    | TIME : 118
                    | ARGS: Reboot(zone:None)
--------------------------------------------------------------------------------
                    | RESULT: passed
                    | TEST NAME: clean_method
                    | TIME : 20
                    | ARGS: clean_method()
--------------------------------------------------------------------------------
RESULTS SUMMARY FOR 'instancetest':

------------------------------------------------------
| TOTAL   | FAILED  | PASSED  | NOT_RUN | TIME_ELAPSED
------------------------------------------------------
| 4       | 1       | 3       | 0       | 205
------------------------------------------------------


-------------------------------------------------------------------------
passed:3 out of total:4
[2013-07-12 08:47:54,061] [instancetest] [DEBUG]: (run_test_case_list:845): </pre>
